version: "3"

services:
  arena-frontend:
    image: arena-frontend
    build: ./arena-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./arena-frontend/components:/home/appuser/components
      - ./arena-frontend/pages:/home/appuser/pages
      - ./arena-frontend/network:/home/appuser/network
      - ./arena-frontend/utils:/home/appuser/utils
      - ./arena-frontend/tailwind.config.js:/home/appuser/tailwind.config.js
      - foxglove-src-volume:/home/appuser/public/lib/foxglove
      - foxglove-models-volume:/home/appuser/public/lib/foxglove-models
    env_file:
      - ./arena-frontend/.env
    networks:
      - app-network

  arena-backend:
    image: arena-backend
    build: ./arena-backend
    ports:
      - "5000:5000"
    volumes:
      - ./arena-backend/endpoints:/home/appuser/endpoints
      - ./arena-backend/utils:/home/appuser/utils
    env_file:
      - ./arena-backend/.env
    depends_on:
      - mongo
    networks:
      - app-network

  foxglove-studio:
    image: foxglove-studio
    build: foxglove-studio
    ports:
      - "8080:8080"
    volumes:
      - ./foxglove-studio/public/lib/foxglove:/src/public/lib/foxglove
      - ./foxglove-studio/public/lib/foxglove-models:/src/public/lib/foxglove-models
      - foxglove-src-volume:/src/public/lib/foxglove
      - foxglove-models-volume:/src/public/lib/foxglove-models
    networks:
      - app-network

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  foxglove-src-volume:
  foxglove-models-volume:
