version: "3"

services:
  arena-frontend:
    image: arena-frontend
    build: ./arena-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./arena-frontend/components:/home/appuser/components
      - ./arena-frontend/pages:/home/appuser/pages
      - ./arena-frontend/network:/home/appuser/network
      - ./arena-frontend/utils:/home/appuser/utils
      - foxglove-src-volume:/public/lib/foxglove
    env_file:
      - ./arena-frontend/.env
    networks:
      - app-network

  arena-backend:
    image: arena-backend
    build: ./arena-backend
    ports:
      - "5000:5000"
    volumes:
      - ./arena-backend/endpoints:/home/appuser/endpoints
      - ./arena-backend/utils:/home/appuser/utils
    env_file:
      - ./arena-backend/.env
    depends_on:
      - mongo
    networks:
      - app-network

  foxglove-studio:
    image: foxglove-studio
    build: foxglove-studio
    ports:
      - "8080:8080"
    volumes:
      - foxglove-src-volume:/src/public/lib/foxglove
    networks:
      - app-network

  ros-bridge:
    image: ros-bridge
    hostname: ros-bridge
    build:
      context: backend
      dockerfile: Dockerfile-ROS-Bridge
    ports:
      - "9090:9090"
    networks:
      - app-network

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  foxglove-src-volume:
